- type: job
  id: MedicalIntern
  name: job-name-intern
  description: job-description-intern
  playTimeTracker: JobMedicalIntern
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 3600 #1 hr # Sunrise-RoleTime
  startingGear: MedicalInternGear
  icon: "JobIconMedicalIntern"
  supervisors: job-supervisors-medicine
  canBeAntag: true # Sunrise-Edit
  displayWeight: 0  # Sunrise-Edit
  access:
  - Medical
  - Maintenance

- type: startingGear
  id: MedicalInternGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: MedicalInternPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    pocket2: BookMedicalReferenceBook
    eyes: ClothingEyesHudMedical # Sunrise-Edit
  #storage:
    #back:
    #- Stuff
