- type: latheRecipePack
  id: SecurityStaticSunrise
  recipes:
    - MagazineMagnumEmpty
    - MagazineMagnum
    - MagazineP90
    - MagazineBR64
    - MagazinePistolHighCapacity
    - MagazinePistolHighCapacityEmpty
    - MagazineMagnum
    - ClothingHeadHelmetPubg

- type: latheRecipePack
  id: SecurityDynamicSunrise
  recipes:
    - WeaponGunLaserCarbineSemi
    - WeaponMechCombatImmolationGun
    - WeaponMechCombatSolarisLaser
    - WeaponMechCombatFiredartLaser
    - WeaponMechCombatUltraRifle
    - WeaponMechCombatMG
    - WeaponMechCombatIon
    - WeaponMechCombatXray
    - WeaponMechCombatShotgun
    - WeaponMechCombatShotgunIncendiary
    - WeaponMechCombatDisabler
    - WeaponMechCombatFlashbangLauncher
    - WeaponMechCombatMissileRack8
    - WeaponEnergyGun
    - WeaponEnergyGunMini
    - WeaponEnergyGunPistol
    - WeaponGunLaserCarbineAutomatic
    - ClothingShoesBootsMagCombat
    - BaseMagazinePistolCaselessRifleExtended
    - MagazinePPSH41Extended
    - MagazineMP5Extended
    - MagazineMP7Extended
    - MagazineP90Extended
    - MagazineM16A4Extended
    - MagazineAR18Extended
    - MagazineM28Extended
    - MagazineG36Extended
    - MagazineFamasExtended
    - MagazineV31Extended
    - MagazineBauer127Extended
    - MagazineBR64Extended
    - MagazineDragunovExtended
    - ShellBlastArtillery
    - ShellEMPArtillery
    - ShellFlashArtillery
    - EnergyDomeDirectionalTurtle
    - ClothingHeadHelmetPubg
    - ClothingShoesBootsMagCombat
    - ClothingShoesBootsMagSec
    - WeaponTemperatureGun
