- type: department
  id: Law
  description: department-Law-description
  color: "#FF5297"
  weight: 80
  roles:
    - Magistrat
    - IAA
    - Lawyer

- type: department
  id: CentralCommand
  description: department-CentralCommand-description
  color: "#048e0f" # Sunrise-Edit
  weight: 120
  roles:
  - CentCommOperator
  primary: false

- type: department # Surnise-Blueshield
  id: Blueshield
  description: department-Blueshield-description
  color: "#1A2AAA"
  roles:
    - BlueShield
  primary: false
  weight: 50

- type: department
  id: PlanetPrison
  sort: 0
  description: department-PlanetPrison-description
  color: "#9f4000"
  roles:
  - HeadOfPrison
  - PrisonPilot
  - PrisonWorker
  - PrisonChef
  - PrisonDoctor
  - PrisonEngineer
  - PrisonGuard
  - Prisoner
