- type: job
  id: CentCommOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentCommOfficial
  requirements:
  - !type:DiscordRoleRequirement
  weight: 30
  setPreference: false
  startingGear: CentCommOfficialGear
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  radioBold: true
  canBeAntag: false
  alwaysUseSpawner: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentCommOfficialGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorCentcomCarapace
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPistolN1984
  storage:
    back:
    - PenCentcom
    - BoxFolderBlack
