- type: job
  id: EngineerBorg
  name: job-name-engineer-borg
  description: job-description-engineer-borg
  playTimeTracker: JobEngineerBorg
  icon: JobIconEngineerBorg
  supervisors: job-supervisors-human
  canBeAntag: false
  displayWeight: -10  # Sunrise
  jobEntity: PlayerBorgEngineerBattery
