- type: job
  id: PeaceBorg
  name: job-name-peace-borg
  description: job-description-peace-borg
  playTimeTracker: JobPeaceBorg
  icon: JobIconPeaceBorg
  supervisors: job-supervisors-hos
  canBeAntag: false
  displayWeight: -10  # Sunrise
  jobEntity: PlayerBorgPeaceBattery
