- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000 #10 hrs # Sunrise-RoleTime
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  displayWeight: 20  # Sunrise
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Detective
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  speciesBlacklist:
  - Vox

- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterFilled
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner
