- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 #5 hrs # Sunrise-RoleTime
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  displayWeight: 10
  access:
  - Security
  - Brig
#  - Maintenance #Sunrise-Edit
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  speciesBlacklist:
  - Vox

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    head: ClothingHeadHelmetBasic
    gloves: ClothingHandsGlovesColorBlack
  storage:
    back:
    - Flash
#    - MagazineGlock22 # Sunrise-Edit
