- type: loadout
  id: SecurityBodycam
  startingGear: SecurityBodycam

- type: startingGear
  id: SecurityBodycam
  storage:
    back:
    - HandheldCamera

- type: loadout
  id: SecurityPepperspray
  startingGear: PeppersprayBlue

- type: startingGear
  id: PeppersprayBlue
  storage:
    back:
    - PepperSprayBottleBlue

- type: loadout
  id: SecurityWhistle
  startingGear: SecurityWhistle

- type: startingGear
  id: SecurityWhistle
  storage:
    back:
    - SecurityWhistle

- type: loadout
  id: SecurityRadioHandheld
  startingGear: SecurityRadioHandheld

- type: startingGear
  id: SecurityRadioHandheld
  storage:
    back:
    - RadioHandheldSecurity

- type: loadout
  id: SecurityTourniquet
  startingGear: SecurityTourniquet

- type: startingGear
  id: SecurityTourniquet
  storage:
    back:
    - Tourniquet

- type: loadout
  id: SecurityGrenadeStinger
  startingGear: SecurityGrenadeStinger

- type: startingGear
  id: SecurityGrenadeStinger
  storage:
    belt:
    - GrenadeStinger

- type: loadout
  id: SecurityClusterBangFull
  startingGear: SecurityClusterBangFull

- type: startingGear
  id: SecurityClusterBangFull
  storage:
    belt:
    - ClusterBangFull

- type: loadout
  id: SecurityTearGasGrenade
  startingGear: SecurityTearGasGrenade

- type: startingGear
  id: SecurityTearGasGrenade
  storage:
    belt:
    - TearGasGrenade

- type: loadout
  id: SecurityWeaponMeleeNeedle
  startingGear: SecurityWeaponMeleeNeedle

- type: startingGear
  id: SecurityWeaponMeleeNeedle
  storage:
    back:
    - WeaponMeleeNeedle

- type: loadout
  id: SecurityHoloprojector
  startingGear: SecurityHoloprojector

- type: startingGear
  id: SecurityHoloprojector
  storage:
    back:
    - HoloprojectorSecurity
