- type: job
  id: NanoTrasenRepresentative
  name: job-name-ntrep
  description: job-description-ntrep
  playTimeTracker: JobNanoTrasenRepresentative
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 62000 # 20 hrs
  startingGear: NanoTrasenRepresentativeGear
  icon: JobIconNanotrasen
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Armory
    - Cryogenics
    - Lawyer
    - Command
    - Bar
    - Service
    - Maintenance
    - Janitor
    - Theatre
    - Kitchen
    - Chapel
    - Hydroponics
    - External
    - Chemistry
    - Engineering
    - Research
    - Detective
    - Salvage
    - Security
    - Brig
    - Cargo
    - Atmospherics
    - Cargo
    - Medical
    - Ntrep
  special:
    - !type:AddImplantSpecial
      implants: [MindShieldImplant]

- type: startingGear
  id: NanoTrasenRepresentativeGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesSunGlassesHudSkill
    head: ClothingHeadHatCapNtrep
    id: NanoTrasenRepresentativePDA
    ears: ClothingHeadsetAltCommand
    pocket1: FlippoEngravedLighter
    pocket2: PenCentcom
  storage:
    back:
    - RubberStampNtrep
    - CaneNT
