- type: job
  id: SeniorPhysician
  name: job-name-senior-physician
  description: job-description-senior-physician
  playTimeTracker: JobSeniorPhysician
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 216000 # 60 hrs
  startingGear: SeniorPhysicianGear
  icon: "JobIconSeniorPhysician"
  supervisors: job-supervisors-cmo
  displayWeight: 35
  access:
  - Medical
  - Maintenance
  - Chemistry

- type: startingGear
  id: SeniorPhysicianGear
  equipment:
    head: ClothingHeadHatBeretSeniorPhysician
    id: SeniorPhysicianPDA
    ears: ClothingHeadsetMedical
    eyes: ClothingEyesUniversalMedicalHud
    outerClothing: ClothingOuterCoatLabSeniorPhysician
  storage:
    back:
    - MedicatedSuture
    - RegenerativeMesh
