- type: department
  id: Cargo
  name: department-Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  - MailCarrier # Sunrise-Roles

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Bartender
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker
  - Barber # Sunrise-Roles

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#0c344d"
  roles:
  - CentCommOperator # Sunrise-Edit
  - CentCommOfficial # Sunrise-Edit
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  editorHidden: true
  weight: 120

- type: department
  id: Command
  name: department-Command
  description: department-Command-description
  color: "#052EED" # Sunrise-Edit
  roles:
  - Captain
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  - CentCommOfficial
  - NanoTrasenRepresentative  #Sunrise-Edit
  - Adjutant  #Sunrise-edit
  primary: false
  weight: 100

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#EFB341"
  weight: 10  # Sunrise-weights
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - SeniorEngineer  # Sunrise-Senior
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - SeniorPhysician  # Sunrise-Senior
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  - MedicalPathologist  # Sunrise-pathologist

- type: department
  id: Security
  name: department-Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - HeadOfSecurity
  - SeniorOfficer  # Sunrise-Senior
  - SecurityCadet
  - SecurityOfficer
  - Detective
  - Warden
  - Brigmedic  # Sunrise-Brigmedic
  - SecurityPilot # Sunrise-SecurityPilot

- type: department
  id: Science
  name: department-Science
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - SeniorResearcher  # Sunrise-Senior
  - Scientist
  - ResearchAssistant
  - Roboticist  # Sunrise-Edit

- type: department
  id: Silicon
  sort: 0
  name: department-Silicon
  description: department-Silicon-description
  color: "#D381C9"
  roles:
  - StationAi
  - Borg
  - MedicalBorg # Sunrise-Edit
  - EngineerBorg # Sunrise-Edit
  - MiningBorg # Sunrise-Edit
  - JanitorBorg # Sunrise-Edit
  - ServiceBorg # Sunrise-Edit
  - ClownBorg # Sunrise-Edit
  - PeaceBorg # Sunrise-Edit
  - SecurityBorg # Sunrise-Edit
  primary: false

- type: department
  id: Specific
  name: department-Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: 5  # Sunrise-weights
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  - Psychologist
  - Barber  # Sunrise-Roles
  primary: false
