- type: department
  id: Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist

- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Bartender
  - Borg
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Lawyer
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker

- type: department
  id: Command
  description: department-Command-description
  color: "#052EED" # Sunrise-Edit
  roles:
  - Captain
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
#  - NanoTrasenRepresentative  #Sunrise-Edit
  primary: false
  weight: 100

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  weight: 10  # Sunrise-weights
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - SeniorEngineer  # Sunrise-Senior
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - SeniorPhysician  # Sunrise-Senior
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - HeadOfSecurity
  - SeniorOfficer  # Sunrise-Senior
  - SecurityCadet
  - SecurityOfficer
  - Detective
  - Warden
  - Brigmedic  # Sunrise-Brigmedic
  - SecurityPilot # Sunrise-SecurityPilot

- type: department
  id: Science
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - SeniorResearcher  # Sunrise-Senior
  - Scientist
  - ResearchAssistant
  - Roboticist  # Sunrise-Edit

- type: department
  id: Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: 5  # Sunrise-weights
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  - Psychologist
  primary: false
