- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 18000 #5 hrs # Sunrise-RoleTime
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 36000 #10 hrs # Sunrise-RoleTime
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  radioBold: true
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - Command
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  speciesBlacklist:
  - Vox

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
