- type: job
  id: PrisonChef
  name: job-name-prison-chef
  description: job-description-prison-chef
  playTimeTracker: JobPrisonChef
  startingGear: ChefGear
  requirements:
  - !type:RoleTimeRequirement
    role: JobChef
    time: 7200 #2 hrs
  icon: "JobIconPrisonChef"
  supervisors: job-supervisors-head-of-prison
  alwaysUseSpawner: true
  canBeAntag: false
  displayWeight: 50
  access:
  - Service
  - Maintenance
  - Kitchen
  - Hydroponics
  - Bar
