- type: job
  id: PrisonEngineer
  name: job-name-prison-engineer
  description: job-description-prison-engineer
  playTimeTracker: JobPrisonEngineer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 7200 # 2 hrs
  alwaysUseSpawner: true
  canBeAntag: false
  startingGear: PrisonEngineerGear
  icon: "JobIconPrisonEngineer"
  overrideConsoleVisibility: false
  supervisors: job-supervisors-head-of-prison
  displayWeight: 70
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: PrisonEngineerGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetJEngineering
    id: PrisonEngineerPDA
  storage:
    back:
    - Flash
