- type: job
  id: PrisonDoctor
  name: job-name-prison-doctor
  description: job-description-prison-doctor
  playTimeTracker: JobPrisonDoctor
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200 # 2 hrs
  alwaysUseSpawner: true
  canBeAntag: false
  startingGear: DoctorGear
  icon: "JobIconPrisonDoctor"
  overrideConsoleVisibility: false
  supervisors: job-supervisors-head-of-prison
  displayWeight: 60
  access:
  - Medical
  - Maintenance
  - Chemistry
