- type: playTimeTracker
  id: JobIAA

- type: playTimeTracker
  id: JobMagistrat

- type: playTimeTracker
  id: JobBrigmedic

- type: playTimeTracker
  id: JobCentCommOperator

- type: playTimeTracker
  id: JobCentCommOfficial

- type: playTimeTracker
  id: JobBlueShield
  
- type: playTimeTracker
  id: JobNanoTrasenRepresentative

- type: playTimeTracker
  id: JobSeniorEngineer

- type: playTimeTracker
  id: JobSeniorOfficer

- type: playTimeTracker
  id: JobSeniorPhysician

- type: playTimeTracker
  id: JobSeniorResearcher

- type: playTimeTracker
  id: JobRoboticist

- type: playTimeTracker
  id: JobSecurityPilot

- type: playTimeTracker
  id: JobPrisonChef

- type: playTimeTracker
  id: JobPrisonWorker

- type: playTimeTracker
  id: JobPrisonGuard

- type: playTimeTracker
  id: JobPrisonPilot

- type: playTimeTracker
  id: JobPrisonDoctor

- type: playTimeTracker
  id: JobHeadOfPrison

- type: playTimeTracker
  id: JobPrisoner

- type: playTimeTracker
  id: JobPrisonEngineer
