- type: playTimeTracker
  id: JobIAA

- type: playTimeTracker
  id: JobMagistrat

- type: playTimeTracker
  id: JobBrigmedic

- type: playTimeTracker
  id: JobMailCarrier

- type: playTimeTracker
  id: JobCentCommOperator

- type: playTimeTracker
  id: JobCentCommOfficial

- type: playTimeTracker
  id: JobBlueShield

- type: playTimeTracker
  id: JobNtrGuard

- type: playTimeTracker
  id: JobNtrLeader

- type: playTimeTracker
  id: JobNtrOfficer

- type: playTimeTracker
  id: JobNanoTrasenRepresentative

- type: playTimeTracker
  id: JobSeniorEngineer

- type: playTimeTracker
  id: JobSeniorOfficer

- type: playTimeTracker
  id: JobSeniorPhysician

- type: playTimeTracker
  id: JobSeniorResearcher

- type: playTimeTracker
  id: JobRoboticist

- type: playTimeTracker
  id: JobSecurityPilot

- type: playTimeTracker
  id: JobPrisonChef

- type: playTimeTracker
  id: JobPrisonWorker

- type: playTimeTracker
  id: JobPrisonGuard

- type: playTimeTracker
  id: JobPrisonPilot

- type: playTimeTracker
  id: JobPrisonDoctor

- type: playTimeTracker
  id: JobHeadOfPrison

- type: playTimeTracker
  id: JobPrisoner

- type: playTimeTracker
  id: JobPrisonEngineer

- type: playTimeTracker
  id: JobEngineerBorg

- type: playTimeTracker
  id: JobJanitorBorg

- type: playTimeTracker
  id: JobMedicalBorg

- type: playTimeTracker
  id: JobMiningBorg

- type: playTimeTracker
  id: JobServiceBorg

- type: playTimeTracker
  id: JobSecurityBorg

- type: playTimeTracker
  id: JobSecurityCombatBorg

- type: playTimeTracker
  id: JobPeaceBorg

- type: playTimeTracker
  id: JobClownBorg

- type: playTimeTracker
  id: JobBarber

- type: playTimeTracker
  id: JobMedicalPathologist

- type: playTimeTracker
  id: JobAdjutant

- type: playTimeTracker
  id: JobUSSPCrew

- type: playTimeTracker
  id: JobUSSPOfficer

- type: playTimeTracker
  id: JobUSSPOfficeraAlt

- type: playTimeTracker
  id: JobUSSPSoldier

- type: playTimeTracker
  id: JobUSSPCaptain
