- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 36000 #10 hrs
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
    - !type:AgeRequirement
      requiredAge: 35 # Sunrise-Edit
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  radioBold: true # Sunrise-Edit
  displayWeight: 50 # Sunrise-Edit
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  speciesBlacklist:
  - Vox # Sunrise-Edit

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    pocket1: HandheldRoboAnalyzer # Sunrise-Edit
    pocket2: Nanopaste10 # Sunrise-Edit
    ears: ClothingHeadsetRD
  storage:
    back:
    - Flash
    - Telebaton # Sunrise-Edit
