- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 36000 #10 hrs # Sunrise-RoleTime
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  radioBold: true
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  speciesBlacklist:
  - Vox

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    pocket1: HandheldRoboAnalyzer
    pocket2: Nanopaste10
    ears: ClothingHeadsetRD
  storage:
    back:
    - Flash
    - Telebaton
