- type: antag
  id: Thief
  name: roles-antag-thief-name
  antagonist: true
  setPreference: true
  playTimeTracker: AntagThief # Sunrise-Edit
  objective: roles-antag-thief-objective
  guides: [ Thieves ]
  # Sunrise-Edit
  previewIcon:
    sprite: /Textures/_Sunrise/Interface/Misc/antag_preview.rsi
    state: thief

- type: startingGear
  id: ThiefGear
  storage:
    back:
    - ThiefBeacon
    - SatchelThief
    - ClothingHandsChameleonThief
