- type: antag
  id: Traitor
  name: roles-antag-syndicate-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-syndicate-agent-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 36000 # 10h # Sunrise-RoleTime
