- type: antag
  id: InitialInfected
  name: roles-antag-initial-infected-name
  antagonist: true
  setPreference: true
  objective: roles-antag-initial-infected-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 54000 # 15h # Sunrise-RoleTime
  guides: [ Zombies ]
  # Sunrise-Edit
  previewIcon:
    sprite: /Textures/_Sunrise/Interface/Misc/antag_preview.rsi
    state: initial_infected

- type: antag
  id: Zombie
  name: roles-antag-zombie-name
  antagonist: true
  setPreference: false
  objective: roles-antag-zombie-objective
  guides: [ Zombies ]
