
- type: job
  id: SeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobSeniorEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 21600 # 6 hrs
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 21600 # 6 hrs
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 216000 # 60 hrs
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  displayWeight: 30
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: SeniorEngineerGear
  equipment:
    head: ClothingHeadHatBeretEngineering
    id: SeniorEngineerPDA
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  storage:
    back:
    - ClothingOuterHardsuitEngineeringCompact
    - RCDAmmo
