- type: entity
  id: MobDisease
  name: sensible disease
  description: plague inc 2.0
  components:
  - type: MindContainer
  - type: InputMover
  - type: MobMover
  - type: Input
    context: "ghost"
  - type: MovementSpeedModifier
    baseWalkSpeed: 6
    baseSprintSpeed: 6
  - type: Sprite
    noRot: true
    drawdepth: Ghosts
    sprite: _Sunrise/Mobs/Aliens/disease.rsi
    layers:
    - state: idle
      shader: unshaded
      map: ["base"]
  - type: Clickable
  - type: InteractionOutline
  - type: Physics
    bodyType: KinematicController
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.40
        density: 80
        mask:
        - GhostImpassable
  - type: MovementIgnoreGravity
  - type: Damageable
    damageContainer: Biological
  - type: Examiner
  - type: NoSlip
  - type: Actions
  - type: Eye
    drawFov: false
    visMask:
      - Normal
      - Ghost
  - type: ContentEye
    maxZoom: 1.2, 1.2
  - type: DoAfter
  - type: Alerts
  - type: GhostRole
    makeSentient: true
    name: ghostrole-disease-name
    description: ghostrole-disease-description
    raffle:
      settings: default
    mindRoles:
    - MindRoleGhostRoleSoloAntagonist
  - type: GhostTakeoverAvailable
  - type: UserInterface
    interfaces:
      enum.StoreUiKey.Key:
        type: StoreBoundUserInterface
  - type: Visibility
    layer: 2 #ghost vis layer
  - type: Store
    categories:
    - DiseaseInfectCategory
    - DiseaseSymptomsCategory
    - DiseaseEvolutionCategory
    currencyWhitelist:
    - DiseasePoints
    balance:
      DiseasePoints: 20
  - type: DiseaseRole
    actions:
      ActionInfect: -1
      ActionDiseaseBaseChance: -1
      ActionDiseaseInfectChance: -1
      ActionDiseaseShield: -1
      ActionDiseaseLethal: -1
  - type: Muted

- type: sickIcon
  id: SmartDiseaseIcon
  icon:
    sprite: /Textures/_Sunrise/Mobs/Aliens/Disease/interface.rsi
    state: sick
  priority: 2

- type: sickIcon
  id: NormalDiseaseIcon
  icon:
    sprite: /Textures/_Sunrise/Mobs/Aliens/Disease/interface.rsi
    state: normal
  priority: 2