- type: job
  id: BlueShield
  name: офицер «синий щит»
  description: Ваша главная задача - защита глав. Помните, вы не офицер службы безопасности.
  playTimeTracker: JobBlueShield
#  requirements:
#  - !type:DepartmentTimeRequirement
#    department: Security
#    time: 36000 # 10 hrs
#  - !type:DepartmentTimeRequirement
#    department: Command
#    time: 36000 # 10 hrs
  startingGear: BlueShieldGear
  icon: JobIconBlueShield
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Command
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Cargo
  - Atmospherics
  - Cargo
  - Medical
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: BlueShieldGear
  equipment:
    shoes: ClothingShoesBootsBlueShieldFilled
    eyes: ClothingEyesGlassesBlueShield
    head: ClothingHeadHatBeretBlueShield
    outerClothing: ClothingOuterArmorBlueShield
    id: BlueShieldPDA
    ears: ClothingHeadsetAltCommand
    belt: ClothingBeltBlueShieldWebbingFilled
    gloves: ClothingHandsGlovesCombat
  inhand:
  - WeaponDisablerSMG
