name: Update Locale

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: read

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    if: github.repository == 'space-sunrise/space-station-14'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Pull Request Number
        id: get_pr
        uses: actions/github-script@v6
        with:
          script: |
            if (context.event_name === 'pull_request') {
              return { PR_NUMBER: context.payload.pull_request.number };
            }
            return { PR_NUMBER: '' };
          result-encoding: string

      - name: Set up Python
        if: steps.get_pr.outputs.PR_NUMBER != ''
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install pyyaml PyGithub pydash fluent

      - name: Find Locale Keys
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python ./Tools/_sunrise/keyfinder.py
          echo "Script exited with code $?"

      - name: Update Yaml Locale Keys
        run: |
          python ./Tools/_sunrise/yamlextractor.py
          echo "Script exited with code $?"

      - name: Git status before commit
        if: steps.get_pr.outputs.PR_NUMBER != ''
        run: |
          git status

      - name: Commit and push changes
        if: steps.get_pr.outputs.PR_NUMBER != ''
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "Resources/Locale/*"
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update locale [skip ci]"
            git push origin HEAD:Starlight
          fi
