name: Update sunrise changelog

on:
  push:
    branches: [master]
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  update_changelog:
    if: github.event.pull_request.merged == true && github.event.commits[0].author.name != 'GitHubActions'
    uses: space-sunrise/space-station-14/.github/workflows/update_changelog.yml@master
    with:
      pr_body: ${{ github.event.pull_request.body }}
    secrets:
      envPAT: ${{ secrets.GH_TOKEN }}
